---
name: _notify

"on":
  workflow_call:
    inputs:
      fork:
        type: string
      ref:
        type: string
      head:
        type: string
      date:
        type: string
      version:
        type: string
      tier2:
        type: boolean
      jit:
        type: boolean
      nogil:
        type: boolean

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - name: Setup system Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - name: Install dependencies from PyPI
        run: |
          pip install -r requirements.txt
      - name: Send notifications
        if: env.WORKFLOW_CONCLUSION == 'success'
        run: python -m bench_runner notify --fork ${{ inputs.fork }} --ref ${{ inputs.ref }} --head ${{ inputs.head }} --date ${{ inputs.date }} --version ${{ inputs.version }} --tier2 ${{ inputs.tier2 }} --jit ${{ inputs.jit }} --nogil ${{ inputs.nogil }}
        env:
          GH_TOKEN: ${{ github.token }}