---
name: _weekly

"on":
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch: {}

jobs:
  # Determine the base commit of the selected commit. The output is passed to
  # the `base` job below. If the data already exists for this commit, it will be
  # skipped.
  determine_head:
    runs-on: ubuntu-latest
    outputs:
      commit: ${{ steps.head.outputs.commit }}
    steps:
      - name: Checkout CPython
        uses: actions/checkout@v4
        with:
          repository: python/cpython
          path: cpython
      - name: Determine head commit
        id: head
        run: |
          cd cpython
          git log -n 1 --format="commit=%H" >> $GITHUB_OUTPUT

  weekly:
    uses: ./.github/workflows/_benchmark.yml
    needs: determine_head
    with:
      fork: python
      ref: ${{ needs.determine_head.outputs.commit }}
      machine: all
      benchmarks: all
      pgo: true
      tier2: false
    secrets: inherit

  weekly-tier2:
    uses: ./.github/workflows/_benchmark.yml
    needs: determine_head
    with:
      fork: python
      ref: ${{ needs.determine_head.outputs.commit }}
      machine: all
      benchmarks: all
      pgo: true
      tier2: true
    secrets: inherit

  pystats:
    uses: ./.github/workflows/_pystats.yml
    needs: determine_head
    with:
      fork: python
      ref: ${{ needs.determine_head.outputs.commit }}
      benchmarks: all
      individual: true
      tier2: false
    secrets: inherit

  pystats-tier2:
    uses: ./.github/workflows/_pystats.yml
    needs: determine_head
    with:
      fork: python
      ref: ${{ needs.determine_head.outputs.commit }}
      benchmarks: all
      individual: true
      tier2: true
    secrets: inherit

  generate:
    uses: ./.github/workflows/_generate.yml
    with:
      force: false
    needs: [weekly, weekly-tier2, pystats, pystats-tier2]
    secrets: inherit

  publish:
    uses: ./.github/workflows/_publish.yml
    needs: [generate]
    secrets: inherit
